language: rust
cache: cargo
matrix:
  include:
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-musl
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin

    # Minimum Rust supported channel.
    - os: linux
      rust: 1.33.0
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: 1.33.0
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: 1.33.0
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: 1.33.0
      env: TARGET=i686-unknown-linux-musl
    - os: osx
      rust: 1.33.0
      env: TARGET=x86_64-apple-darwin

addons:
  apt:
    packages:
      # needed for i686-unknown-linux-gnu target
      - gcc-multilib

env:
  global:
    # Default target on travis-ci.
    # Used as conditional check in the install stage
    - HOST=x86_64-unknown-linux-gnu
    # Used on the deployment script
    - PROJECT_NAME=sub

install:
  # prevent target re-add error from rustup
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

script:
  # Incorporate TARGET env var to the build and test process
  - cargo build --target $TARGET --verbose
  - cargo test --target $TARGET --verbose
