[package]
name = "sub"
description = "A command-line tool for string substitutions"
version = "0.1.0"
authors = ["David Peter <mail@david-peter.de>"]
edition = "2018"

[dependencies]
clap = "2"
regex = "1"
tempfile = "3"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1.0"
